In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  8 19:58:25 2017
Purpose: Given a set of tweets with pre-defined labels, use 3 Supervised Learning algorithms to 
predict the sentiment of tweets that were directed at US airlines. 
Compare the accuracy of the three algorithms.
@author: Simone
"""
#------------------------------------------------------------------------------Import the dataset and the libraries

# Import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
# # import StemmerFactory class
# from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# # create stemmer
# factory = StemmerFactory()
# stemmer = factory.create_stemmer()

# # stemming process
# sentence = 'Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan'
# output   = stemmer.stem(sentence)

# print(output)
# # ekonomi indonesia sedang dalam tumbuh yang bangga

# print(stemmer.stem('Mereka meniru-nirukannya'))
# # mereka tiru

ekonomi indonesia sedang dalam tumbuh yang bangga
mereka tiru


In [35]:
# corpus = []
# for line in open('data/neg.txt'):
#     line = stemmer.stem(line)
#     corpus.append(line)

# for line in open('data/pos.txt'):
#     line = stemmer.stem(line)
#     corpus.append(line)

In [8]:
corpus = open('data/clean_neg.txt').read().replace('\n', '')

In [11]:
print(corpus[:100])

kok mahal banget yaitu belum lakuanggap sebut salahkrisis belum akan akhircuma saya kan tidak bisa b


In [15]:
corpus = []

import re, string
for line in open('data/clean_neg.txt'):
    line = line.replace("\n","")
    corpus.append(line)
    
for line in open('data/clean_pos.txt'):
    line = line.replace("\n","")
    corpus.append(line)

In [16]:
len(corpus)

2000

In [17]:
print(corpus[:10])

['kok mahal banget ya', 'itu belum laku', 'anggap sebut salah', 'krisis belum akan akhir', 'cuma saya kan tidak bisa buka', 'restrukturisasi utang yang masalah', 'korban tewas akibat overdosis minum keras', 'sungguh buah momen keri yang nyata', 'tugas masih di lapang belum dapat info', 'jumlah ini terlalu banyak ideal 24 main']


In [18]:
print(corpus[-10:])

['dia gingrich dapat dukung dari pilih tea party 61-21 anggota republik daftar 38-30 pilih konservatif 41-21 lelaki 39-27 dan pilih di dalam', 'sama seperti sekolah kan ada daftar aku dan sama dengan begitu ssb juga akan kejar standar ini sehingga masing-masing akan lomba agar ssb-nya akan lebih baik', 'kira 38 720 ajar sekolah swasta di seluruh negara libat dalam bantu fasa pertama itu dan mereka patut terima bantu rm100 bagi tiap ajar mula malam', 'dewan upah daerah harus kerja cara efektif karena lembaga itu yang beri tugas dan tanggung jawab untuk tetap upah ini sesuai dengan tentu yang laku', 'turut pandang mereka kunjung kapal perang rusia jadi tanda solidaritas dengan suriah bahwa negara itu sangat harga sikap hormat rusia dalam dukung rakyat suriah', 'wujud target yang beban ketua umum itu dalam skala ranah mang butuh kerja keras dan solid seluruh stakeholders pan utama di dalam bela penting rakyat', 'tetapi saya sudah puas karena sesuai hasil seluruh saya masih tetap jadi juar

In [37]:
# Create the Bag of Words for the independent variable
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() #initially 15000+ returned.
X = cv.fit_transform(corpus).toarray()

In [38]:
data_coba = 'semoga bisa'
data_coba = np.array([data_coba])

In [39]:
print(data_coba)

['semoga bisa']


In [40]:
coba = cv.transform(data_coba).toarray()

In [41]:
coba.shape

(1, 4792)

In [42]:
import pickle
pickle.dump(cv, open('CountVectorizer.sav', 'wb'))

In [43]:
cv = pickle.load(open('CountVectorizer.sav', 'rb'))
y = cv.transform(data_coba).toarray()
y.shape

(1, 4792)

Object `Y` not found.


In [22]:
print(X.shape)

(2000, 4792)


In [165]:
X[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [166]:
y = []
for i in range(1,2001):
    if i<=1000:
        y.append(0)
    else:
        y.append(1)

In [167]:
print(y)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [168]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [169]:
y.shape

(2000,)

In [170]:
#------------------------------------------------------------------------------Model Training and Testing

# Split the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 123)

In [171]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
bayes_classifier = GaussianNB()
bayes_classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [172]:
# Fitting the Decision Tree model to the Training set
from sklearn.tree import DecisionTreeClassifier
dec_tree_classifier = DecisionTreeClassifier()
dec_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [173]:
# Fitting the Random Forest model to the Training set
from sklearn.ensemble import RandomForestClassifier
ranforest_classifier = RandomForestClassifier()
ranforest_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [174]:
# Predicting the Test set results for different models
y_pred_bayes = bayes_classifier.predict(X_test)
y_pred_dec_tree = dec_tree_classifier.predict(X_test)
y_pred_ranforest = ranforest_classifier.predict(X_test)

In [175]:
# Making the Confusion Matrix for different models
from sklearn.metrics import confusion_matrix
bayes_cm = confusion_matrix(y_test, y_pred_bayes)
dec_tree_cm = confusion_matrix(y_test, y_pred_dec_tree)
ranforest_cm = confusion_matrix(y_test, y_pred_ranforest)

In [176]:
#------------------------------------------------------------------------------Evaluation:

#My Own from CM:
bayes_negative_accuracy = bayes_cm[0][0]/(bayes_cm[0][0]+bayes_cm[0][1])*100
print("Bayes Negative Accuracy: " + str(bayes_negative_accuracy))

bayes_positive_accuracy = bayes_cm[1][1]/(bayes_cm[1][0]+bayes_cm[1][1])*100
print("Bayes Positive Accuracy: " + str(bayes_positive_accuracy))

dec_tree_negative_accuracy = dec_tree_cm[0][0]/(dec_tree_cm[0][0]+dec_tree_cm[0][1])*100
print("Decision Tree Negative Accuracy: " + str(dec_tree_negative_accuracy))

dec_tree_positive_accuracy = dec_tree_cm[1][1]/(dec_tree_cm[1][0]+dec_tree_cm[1][1])*100
print("Decision Tree Positive Accuracy: " + str(dec_tree_positive_accuracy))

ranforest_negative_accuracy = ranforest_cm[0][0]/(ranforest_cm[0][0]+ranforest_cm[0][1])*100
print("Random Forest Negative Accuracy: " + str(ranforest_negative_accuracy))

ranforest_positive_accuracy = bayes_cm[1][1]/(ranforest_cm[1][0]+ranforest_cm[1][1])*100
print("Random Forest Positive Accuracy: " + str(ranforest_positive_accuracy))

Bayes Negative Accuracy: 72.46376811594203
Bayes Positive Accuracy: 69.94818652849742
Decision Tree Negative Accuracy: 64.73429951690821
Decision Tree Positive Accuracy: 69.43005181347151
Random Forest Negative Accuracy: 73.42995169082126
Random Forest Positive Accuracy: 69.94818652849742


In [177]:
print(y_pred_bayes[:37])
print(y_pred_dec_tree[:37])
print(y_pred_ranforest[:37])
print(y_test[:37])

[1 1 0 1 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 0]
[1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0]
[1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1]
[1 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 1 1 0 0 0]


In [178]:
#Classification Report

from sklearn.metrics import classification_report
bayes_report = classification_report(y_test, y_pred_bayes)
print(bayes_report)

dec_tree_report = classification_report(y_test, y_pred_dec_tree)
print(dec_tree_report)

ranforest_report = classification_report(y_test, y_pred_ranforest)
print(ranforest_report)

             precision    recall  f1-score   support

          0       0.72      0.72      0.72       207
          1       0.70      0.70      0.70       193

avg / total       0.71      0.71      0.71       400

             precision    recall  f1-score   support

          0       0.69      0.65      0.67       207
          1       0.65      0.69      0.67       193

avg / total       0.67      0.67      0.67       400

             precision    recall  f1-score   support

          0       0.73      0.73      0.73       207
          1       0.72      0.72      0.72       193

avg / total       0.72      0.72      0.72       400



In [179]:
dec_tree = dec_tree_classifier.score(X_test, y_test)
print(dec_tree)

0.67


In [180]:
ranforest = ranforest_classifier.score(X_test, y_test)
print(ranforest)

0.725


In [181]:
# import pickle
# # save the model to disk
# pickle.dump(dec_tree_classifier, open('dec_tree.sav', 'wb'))
# pickle.dump(ranforest_classifier, open('ranforest.sav', 'wb'))

In [47]:
# load the model from disk
dec_tree_classifier = pickle.load(open('dec_tree.sav', 'rb'))
ranforest_classifier = pickle.load(open('ranforest.sav', 'rb'))

In [52]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

user_query = '''Seluruh orang di tim bermain bagus (lawan Brighton) dan saya senang 
                bisa mencetak gol dan tentu saja saya juga bahagia untuk 
                Luis Suarez (yang juga mengemas gol setelah gagal penalti),'''

# vectorize the user's query and make a prediction
y = stemmer.stem(user_query)

# cv = CountVectorizer() #initially 15000+ returned.
y = cv.transform(np.array([y])).toarray()

y_pred_dec_tree = dec_tree_classifier.predict(y)
y_pred_ranforest = ranforest_classifier.predict(y)

# Output either 'Negative' or 'Positive' along with the score
if y_pred_dec_tree == 0:
    dec_tree_result = 'Negative'
else:
    dec_tree_result = 'Positive'

if y_pred_ranforest == 0:
    ranforest_result = 'Negative'
else:
    ranforest_result = 'Positive'

print('decision tree:', dec_tree_result, '\nrandom forest:', ranforest_result)

decision tree: Positive 
random forest: Positive
